mqttconfig:
  queueSize: 10
  serverUrls: tcp://192.168.18.190:1883
  userName: admin
  password: password
  readTopic: final_iotgateway
  writeTopic: testTopic
  completionTimeout: 5000
  qos: 1
  clientId: bjy
server:
  port: 8081
